@extends('layouts.app')

@section('content')
    @if(in_array($page, ['dashboard', 'resumen'], true))
        @include('pages.dashboard')
    @elseif(in_array($page, ['horarios', 'horario'], true))
        @include('pages.schedule')
    @elseif($page === 'aula-virtual')
        @include('pages.virtual-classroom')
    @elseif($page === 'tramites')
        @include('pages.transactions')
    @elseif($page === 'activos')
        @include('pages.assets')
    @elseif($page === 'catalogo')
        @include('pages.catalog')
    @elseif($page === 'mapa')
        @include('pages.map')
    @elseif(in_array($page, ['recursos', 'formatos'], true))
        @include('pages.resources')
    @elseif($page === 'infraestructura')
        @include('pages.infrastructure')
    @elseif($page === 'estructura-academica')
        @include('pages.academic')
    @elseif(in_array($page, ['cursos'], true))
        @include('pages.courses')
    @elseif(in_array($page, ['calificaciones', 'rendimiento'], true))
        @include('pages.performance')
    @elseif($page === 'comunicaciones')
        @include('pages.communications')
    @else
        @include('pages.records')
    @endif
@endsection
