<div class="virtual-page-heading"><div><small>AULA VIRTUAL</small><h1>Área personal</h1><p>{{ $isTeacher ? 'Tu resumen de docencia y evaluación para el periodo 2026-1.' : 'Tu espacio de seguimiento académico para el periodo 2026-1.' }}</p></div><div class="student-avatar">{{ $isTeacher ? 'RS' : 'JP' }}</div></div>

<div class="virtual-stat-grid personal-stats">
    @foreach($isTeacher ? [['notebook-tabs','3','Cursos impartidos','blue'],['users','83','Estudiantes','green'],['clipboard-clock','22','Entregas por revisar','amber'],['message-square','2','Mensajes nuevos','red']] : [['notebook-tabs','3','Cursos inscritos','blue'],['circle-check-big','8','Actividades completadas','green'],['list-checks','3','Actividades pendientes','amber'],['chart-spline',$student['average'],'Promedio general','red']] as $stat)<article class="panel"><span class="tone-{{ $stat[3] }}"><i data-lucide="{{ $stat[0] }}"></i></span><strong>{{ $stat[1] }}</strong><small>{{ $stat[2] }}</small></article>@endforeach
</div>

<div class="personal-grid">
    <section class="panel span-2"><div class="panel-header"><div><small>LÍNEA DE TIEMPO</small><h2>{{ $isTeacher ? 'Pendientes de docencia' : 'Próximas actividades' }}</h2></div><select class="select-control"><option>Próximos 7 días</option><option>Próximos 30 días</option></select></div><div class="activity-list">@foreach($isTeacher ? [['HOY','clipboard-pen','Revisar 7 entregas','Sistemas Eléctricos de Potencia','18:00'],['31 AGO','megaphone','Publicar guía de laboratorio','Máquinas Eléctricas II','16:00'],['02 SEP','calendar-check','Cerrar práctica de Control PID','Control Automático','23:59']] : [['31 AGO','clipboard-check','Cuestionario: Flujo de potencia','Sistemas Eléctricos de Potencia','23:59'],['02 SEP','file-up','Informe: Motor trifásico','Máquinas Eléctricas II','20:00'],['04 SEP','flask-conical','Práctica: Control PID','Control Automático','23:59']] as $activity)<button data-toast="Actividad abierta"><time>{{ $activity[0] }}</time><span><i data-lucide="{{ $activity[1] }}"></i></span><div><b>{{ $activity[2] }}</b><small>{{ $activity[3] }}</small></div><em>{{ $activity[4] }}</em><i data-lucide="chevron-right"></i></button>@endforeach</div></section>
    <aside class="panel mini-month"><div class="panel-header"><div><small>CALENDARIO</small><h2>Agosto 2026</h2></div><a href="{{ route('portal',['role'=>$role,'page'=>'aula-virtual','vista'=>'calendario']) }}">Completo</a></div><div class="mini-month-grid">@foreach(['L','M','M','J','V','S','D'] as $dayName)<b>{{ $dayName }}</b>@endforeach @foreach(range(1,31) as $calendarDay)<button class="{{ in_array($calendarDay,[27,31]) ? 'has-event' : '' }} {{ $calendarDay===27 ? 'is-today':'' }}" data-toast="{{ $calendarDay===31 ? 'Cuestionario: Flujo de potencia' : 'Sin actividades registradas' }}">{{ $calendarDay }}</button>@endforeach</div></aside>
</div>
