<?php

namespace App\Support;

final class DemoData
{
    public static function all(): array
    {
        return [
            'student' => [
                'name' => 'Juan Carlos Pérez López', 'firstName' => 'Juan Carlos', 'code' => '202145678',
                'career' => 'Educación General Básica Superior', 'semester' => '8.º EGB · Paralelo A', 'period' => '2026-2027',
                'average' => '8,74', 'attendance' => '94%',
            ],
            'catalog' => [
                ['id' => 'EQ001', 'serial' => 'MIC-1001', 'name' => 'Microscopio binocular escolar', 'category' => 'Ciencias', 'stock' => 8, 'total' => 10, 'location' => 'Laboratorio de Ciencias', 'image' => 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&h=420&fit=crop'],
                ['id' => 'EQ002', 'serial' => 'KIT-2005', 'name' => 'Kit de experimentación de química', 'category' => 'Ciencias', 'stock' => 12, 'total' => 15, 'location' => 'Laboratorio de Ciencias', 'image' => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&h=420&fit=crop'],
                ['id' => 'EQ003', 'serial' => 'ROB-001', 'name' => 'Kit educativo de robótica', 'category' => 'Tecnología', 'stock' => 6, 'total' => 10, 'location' => 'Laboratorio de Cómputo', 'image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=420&fit=crop'],
                ['id' => 'EQ004', 'serial' => 'TAB-1200', 'name' => 'Tableta para aprendizaje interactivo', 'category' => 'Tecnología', 'stock' => 18, 'total' => 25, 'location' => 'Aula Multimedia', 'image' => 'https://images.unsplash.com/photo-1560785496-3c9d27877182?w=600&h=420&fit=crop'],
                ['id' => 'EQ005', 'serial' => 'GLO-3D01', 'name' => 'Globo terráqueo didáctico', 'category' => 'Didáctico', 'stock' => 5, 'total' => 6, 'location' => 'Biblioteca', 'image' => 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=600&h=420&fit=crop'],
                ['id' => 'EQ007', 'serial' => 'PROY-012', 'name' => 'Proyector Epson PowerLite X51+', 'category' => 'Tecnológico', 'stock' => 1, 'total' => 2, 'location' => 'Aula Magna', 'image' => 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&h=420&fit=crop'],
                ['id' => 'EQ008', 'serial' => 'PC-3001', 'name' => 'Computadora HP ProDesk i7', 'category' => 'Tecnológico', 'stock' => 12, 'total' => 20, 'location' => 'Lab. Cómputo 1', 'image' => 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=600&h=420&fit=crop'],
                ['id' => 'EQ011', 'serial' => 'LIB-LECT-01', 'name' => 'Colección de lectura juvenil', 'category' => 'Biblioteca', 'stock' => 24, 'total' => 30, 'location' => 'Biblioteca', 'image' => 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&h=420&fit=crop'],
            ],
            'inventory' => [
                ['code' => 'EQ001', 'name' => 'Microscopio binocular escolar', 'category' => 'Ciencias', 'location' => 'Laboratorio de Ciencias', 'status' => 'Bueno'],
                ['code' => 'EQ002', 'name' => 'Kit de experimentación química', 'category' => 'Ciencias', 'location' => 'Laboratorio de Ciencias', 'status' => 'Malo'],
                ['code' => 'EQ008', 'name' => 'Kit educativo de robótica', 'category' => 'Tecnología', 'location' => 'Sala de Computación', 'status' => 'Bueno'],
                ['code' => 'EQ003', 'name' => 'Computadora Core i7', 'category' => 'Tecnológico', 'location' => 'Sala de Computación', 'status' => 'Bueno'],
                ['code' => 'EQ004', 'name' => 'Computadora Core i7', 'category' => 'Tecnológico', 'location' => 'Sala de Computación', 'status' => 'Dañado'],
                ['code' => 'EQ007', 'name' => 'Proyector Epson PowerLite', 'category' => 'Tecnológico', 'location' => 'Aula 8A', 'status' => 'Bueno'],
            ],
            'requests' => [
                ['id' => 'SOL-2026-041', 'subject' => 'Ciencias Naturales', 'items' => '2 × Microscopio escolar', 'date' => '25 ago 2026', 'status' => 'Aprobada'],
                ['id' => 'SOL-2026-038', 'subject' => 'Computación', 'items' => '4 × Kit de robótica', 'date' => '22 ago 2026', 'status' => 'Pendiente'],
                ['id' => 'SOL-2026-031', 'subject' => 'Lengua y Literatura', 'items' => '12 × Novela juvenil', 'date' => '14 ago 2026', 'status' => 'Entregada'],
                ['id' => 'SOL-2026-024', 'subject' => 'Estudios Sociales', 'items' => '2 × Mapas del Ecuador', 'date' => '02 ago 2026', 'status' => 'Rechazada'],
            ],
            'schedule' => [
                ['time' => '07:00 - 09:00',
                    'monday' => ['subject' => 'Matemática', 'room' => 'Aula 8A', 'type' => 'normal', 'teacher' => 'Lcdo. Roberto Sánchez', 'career' => '8.º EGB'],
                    'tuesday' => ['subject' => 'Lengua y Literatura', 'room' => 'Aula 8A', 'type' => 'normal', 'teacher' => 'Lcda. Patricia Morales', 'career' => '8.º EGB'],
                    'wednesday' => ['subject' => 'Matemática', 'room' => 'Aula 8A', 'type' => 'normal', 'teacher' => 'Lcdo. Roberto Sánchez', 'career' => '8.º EGB'],
                    'thursday' => ['subject' => 'Ciencias Naturales', 'room' => 'Lab. Ciencias', 'type' => 'lab', 'teacher' => 'Lcda. Ana Gómez', 'career' => '8.º EGB'],
                    'friday' => ['subject' => 'English · Reading', 'room' => 'Aula de Idiomas', 'type' => 'normal', 'teacher' => 'Miss Carolina Mendoza', 'career' => '8.º EGB']],
                ['time' => '09:00 - 10:00',
                    'monday' => null,
                    'tuesday' => null,
                    'wednesday' => ['subject' => 'Educación Cultural y Artística', 'room' => 'Taller de Arte', 'type' => 'lab', 'teacher' => 'Lcda. Sofía Naranjo', 'career' => '8.º EGB'],
                    'thursday' => null,
                    'friday' => null],
                ['time' => '10:00 - 12:00',
                    'monday' => ['subject' => 'Ciencias Naturales', 'room' => 'Lab. Ciencias', 'type' => 'lab', 'teacher' => 'Lcda. Ana Gómez', 'career' => '8.º EGB'],
                    'tuesday' => ['subject' => 'Estudios Sociales', 'room' => 'Aula 8A', 'type' => 'normal', 'teacher' => 'Lcdo. Fernando Ruiz', 'career' => '8.º EGB'],
                    'wednesday' => ['subject' => 'Lengua y Literatura', 'room' => 'Biblioteca', 'type' => 'normal', 'teacher' => 'Lcda. Patricia Morales', 'career' => '8.º EGB'],
                    'thursday' => ['subject' => 'Computación', 'room' => 'Lab. Cómputo', 'type' => 'lab', 'teacher' => 'Lcdo. Carlos Mendoza', 'career' => '8.º EGB'],
                    'friday' => ['subject' => 'Tutoría y Valores', 'room' => 'Aula 8A', 'type' => 'tutoria', 'teacher' => 'Lcdo. Roberto Sánchez', 'career' => '8.º EGB']],
                ['time' => '14:00 - 16:00',
                    'monday' => ['subject' => 'Educación Física', 'room' => 'Cancha cubierta', 'type' => 'lab', 'teacher' => 'Lcdo. Diego Vera', 'career' => '8.º EGB'],
                    'tuesday' => ['subject' => 'Proyecto interdisciplinario', 'room' => 'Aula Multimedia', 'type' => 'normal', 'teacher' => 'Lcdo. Roberto Sánchez', 'career' => '8.º EGB'],
                    'wednesday' => ['subject' => 'French', 'room' => 'Aula de Idiomas', 'type' => 'normal', 'teacher' => 'Mme. Valérie León', 'career' => '8.º EGB'],
                    'thursday' => ['subject' => 'Club de Ciencias', 'room' => 'Huerto escolar', 'type' => 'lab', 'teacher' => 'Lcda. Ana Gómez', 'career' => '8.º EGB'],
                    'friday' => null],
            ],
            'buildings' => [
                ['name' => 'Bloque EGB', 'floors' => [
                    ['label' => 'Planta baja', 'rooms' => ['Aula 5A', 'Aula 6A', 'Biblioteca']],
                    ['label' => 'Piso 1', 'rooms' => ['Aula 7A', 'Aula 8A']],
                    ['label' => 'Piso 2', 'rooms' => ['Aula 9A', 'Aula 10A']],
                ]],
                ['name' => 'Bloque de Ciencias', 'floors' => [
                    ['label' => 'Planta baja', 'rooms' => ['Laboratorio de Ciencias', 'Huerto escolar']],
                    ['label' => 'Piso 1', 'rooms' => ['Taller de Arte', 'Aula de Idiomas']],
                ]],
                ['name' => 'Bloque Tecnológico', 'floors' => [
                    ['label' => 'Planta baja', 'rooms' => ['Sala de Computación', 'Aula Multimedia']],
                ]],
            ],
            'campus' => [
                'stats' => ['buildings' => 9, 'spaces' => 84, 'classrooms' => 49, 'labs' => 35],
                'center' => ['lat' => -1.65605, 'lng' => -78.67795],
                'buildings' => [
                    [
                        'id' => 'edificio-aulas', 'name' => 'Edificio de Aulas', 'status' => 'Operativo', 'place' => 'Campus Politécnico',
                        'floors' => 3, 'area' => 400, 'occupancy' => 0, 'lat' => -1.65572, 'lng' => -78.67712,
                        'photo' => 'https://images.unsplash.com/photo-1562774053-701939374585?w=640&h=420&fit=crop',
                        'spaces' => [
                            ['name' => 'Aula 102', 'floor' => 1, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 30, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 103', 'floor' => 1, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 30, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Lab. Telecomunicaciones 1', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 20, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=640&h=420&fit=crop'],
                            ['name' => 'Lab. Telecomunicaciones 2', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 20, 'area' => 60, 'status' => 'Ocupada', 'photo' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 201', 'floor' => 2, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 32, 'area' => 64, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 202', 'floor' => 2, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 32, 'area' => 64, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 203', 'floor' => 2, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 28, 'area' => 58, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 204', 'floor' => 2, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 28, 'area' => 58, 'status' => 'Mantenimiento', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 205', 'floor' => 2, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 30, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 301', 'floor' => 3, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 35, 'area' => 70, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 302', 'floor' => 3, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 35, 'area' => 70, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 303', 'floor' => 3, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 30, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 304', 'floor' => 3, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 30, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula 305', 'floor' => 3, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 30, 'area' => 60, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                        ],
                    ],
                    [
                        'id' => 'bloque-laboratorios', 'name' => 'Bloque de Laboratorios', 'status' => 'Operativo', 'place' => 'Campus Politécnico',
                        'floors' => 2, 'area' => 980, 'occupancy' => 62, 'lat' => -1.65642, 'lng' => -78.67668,
                        'photo' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=640&h=420&fit=crop',
                        'spaces' => [
                            ['name' => 'Lab. Circuitos', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 24, 'area' => 72, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=640&h=420&fit=crop'],
                            ['name' => 'Lab. Control', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 22, 'area' => 68, 'status' => 'Ocupada', 'photo' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=640&h=420&fit=crop'],
                            ['name' => 'Laboratorio de Ciencias', 'floor' => 2, 'kind' => 'Laboratorio', 'category' => 'Académica', 'capacity' => 28, 'area' => 84, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=640&h=420&fit=crop'],
                            ['name' => 'Lab. Electrónica', 'floor' => 2, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 24, 'area' => 72, 'status' => 'Mantenimiento', 'photo' => 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=640&h=420&fit=crop'],
                        ],
                    ],
                    [
                        'id' => 'centro-computo', 'name' => 'Centro de Cómputo', 'status' => 'Operativo', 'place' => 'Campus Politécnico',
                        'floors' => 1, 'area' => 640, 'occupancy' => 48, 'lat' => -1.65688, 'lng' => -78.67781,
                        'photo' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=640&h=420&fit=crop',
                        'spaces' => [
                            ['name' => 'Lab. Cómputo 1', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 30, 'area' => 90, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=640&h=420&fit=crop'],
                            ['name' => 'Lab. Cómputo 2', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 30, 'area' => 90, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=640&h=420&fit=crop'],
                            ['name' => 'Sala de Servidores', 'floor' => 1, 'kind' => 'Laboratorio', 'category' => 'Técnico', 'capacity' => 8, 'area' => 24, 'status' => 'Ocupada', 'photo' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=640&h=420&fit=crop'],
                        ],
                    ],
                    [
                        'id' => 'bloque-administrativo', 'name' => 'Bloque Administrativo', 'status' => 'Mantenimiento', 'place' => 'Campus Politécnico',
                        'floors' => 2, 'area' => 520, 'occupancy' => 30, 'lat' => -1.6552, 'lng' => -78.6784,
                        'photo' => 'https://images.unsplash.com/photo-1562774053-701939374585?w=640&h=420&fit=crop',
                        'spaces' => [
                            ['name' => 'Sala Docentes', 'floor' => 1, 'kind' => 'Oficina', 'category' => 'Académica', 'capacity' => 12, 'area' => 36, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Secretaría General', 'floor' => 1, 'kind' => 'Oficina', 'category' => 'Administrativa', 'capacity' => 6, 'area' => 24, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                            ['name' => 'Aula Magna', 'floor' => 2, 'kind' => 'Aula', 'category' => 'Académica', 'capacity' => 120, 'area' => 320, 'status' => 'Disponible', 'photo' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=640&h=420&fit=crop'],
                        ],
                    ],
                ],
            ],
            'academic' => [
                'faculty' => ['acronym' => 'UEM', 'name' => 'Unidad Educativa Montessori', 'dean' => 'MsC. Marco Aquino', 'status' => 'Activa', 'color' => '#b00000', 'icon' => 'school'],
                'palette' => ['#a855f7', '#2563eb', '#10b981', '#ea580c', '#e11d48', '#0e7490', '#c026d3', '#f97316'],
                'icons' => ['cpu', 'flask-conical', 'building-2', 'stethoscope', 'globe', 'palette', 'microscope', 'pen-tool', 'monitor', 'zap', 'database', 'activity', 'calculator', 'compass', 'leaf', 'network', 'wifi', 'book-open', 'school'],
                'careers' => [
                    ['slug' => 'inicial', 'name' => 'Educación Inicial', 'director' => 'Lcda. María Torres', 'color' => '#a855f7', 'icon' => 'shapes', 'paos' => 2, 'subjects' => 6, 'status' => 'Activa'],
                    ['slug' => 'preparatoria', 'name' => 'Preparatoria', 'director' => 'Lcda. Diana Vallejo', 'color' => '#2563eb', 'icon' => 'puzzle', 'paos' => 1, 'subjects' => 7, 'status' => 'Activa'],
                    ['slug' => 'egb-elemental', 'name' => 'EGB Elemental', 'director' => 'Lcdo. Luis Herrera', 'color' => '#0ea5e9', 'icon' => 'book-open', 'paos' => 3, 'subjects' => 8, 'status' => 'Activa'],
                    ['slug' => 'egb-media', 'name' => 'EGB Media', 'director' => 'Lcda. Ana Gómez', 'color' => '#10b981', 'icon' => 'school', 'paos' => 3, 'subjects' => 9, 'status' => 'Activa'],
                    ['slug' => 'egb-superior', 'name' => 'EGB Superior', 'director' => 'Lcdo. Roberto Sánchez', 'color' => '#f59e0b', 'icon' => 'library', 'paos' => 3, 'subjects' => 10, 'status' => 'Activa'],
                    ['slug' => 'bachillerato', 'name' => 'Bachillerato General Unificado', 'director' => 'Lcda. Patricia Morales', 'color' => '#ea580c', 'icon' => 'graduation-cap', 'paos' => 3, 'subjects' => 12, 'status' => 'Activa'],
                ],
                'curriculum' => [
                    'egb-superior' => [
                        ['code' => 'MAT-8', 'name' => 'Matemática', 'credits' => 5, 'hours' => 200, 'pao' => 8],
                        ['code' => 'LYL-8', 'name' => 'Lengua y Literatura', 'credits' => 5, 'hours' => 200, 'pao' => 8],
                        ['code' => 'CCNN-8', 'name' => 'Ciencias Naturales', 'credits' => 4, 'hours' => 160, 'pao' => 8],
                        ['code' => 'EESS-8', 'name' => 'Estudios Sociales', 'credits' => 4, 'hours' => 160, 'pao' => 8],
                        ['code' => 'ING-8', 'name' => 'English', 'credits' => 3, 'hours' => 120, 'pao' => 8],
                    ],
                ],
            ],
            'users' => [
                ['name' => 'José Enrique Allauca', 'email' => 'jose.allauca@montessori.edu.ec', 'role' => 'Administrador', 'department' => 'Rectorado', 'status' => 'Activo', 'last_seen' => '27/8/2026, 11:36:09 p. m.'],
                ['name' => 'Braulio Paul Balseca', 'email' => 'braulio.balseca@montessori.edu.ec', 'role' => 'Administrador', 'department' => 'Coordinación Académica', 'status' => 'Activo', 'last_seen' => '11/8/2026, 7:51:33 a. m.'],
                ['name' => 'Mgs. Andrea López', 'email' => 'andrea.lopez@montessori.edu.ec', 'role' => 'Administrador', 'department' => 'Secretaría General', 'status' => 'Activo', 'last_seen' => '26/8/2026, 4:12:40 p. m.'],
                ['name' => 'Lcdo. Roberto Sánchez', 'email' => 'roberto.sanchez@montessori.edu.ec', 'role' => 'Docente', 'department' => 'Matemática · EGB Superior', 'status' => 'Activo', 'last_seen' => '27/8/2026, 9:04:12 a. m.'],
                ['name' => 'Lcda. Patricia Morales', 'email' => 'patricia.morales@montessori.edu.ec', 'role' => 'Docente', 'department' => 'Lengua y Literatura', 'status' => 'Activo', 'last_seen' => '27/8/2026, 8:22:05 a. m.'],
                ['name' => 'Lcdo. Carlos Mendoza', 'email' => 'carlos.mendoza@montessori.edu.ec', 'role' => 'Docente', 'department' => 'Computación', 'status' => 'Activo', 'last_seen' => '25/8/2026, 3:47:19 p. m.'],
                ['name' => 'Lcda. Ana Gómez', 'email' => 'ana.gomez@montessori.edu.ec', 'role' => 'Docente', 'department' => 'Ciencias Naturales', 'status' => 'Activo', 'last_seen' => 'Sin registro'],
                ['name' => 'María Fernanda Ruiz', 'email' => 'maria.ruiz@estudiantes.montessori.edu.ec', 'role' => 'Estudiante', 'department' => '8.º EGB · Paralelo A', 'status' => 'Activo', 'last_seen' => '27/8/2026, 7:15:02 a. m.'],
                ['name' => 'Juan Carlos Pérez', 'email' => 'juan.perez@estudiantes.montessori.edu.ec', 'role' => 'Estudiante', 'department' => '8.º EGB · Paralelo A', 'status' => 'Activo', 'last_seen' => '26/8/2026, 10:58:33 p. m.'],
                ['name' => 'Jorge Silva Andrade', 'email' => 'jorge.silva@estudiantes.montessori.edu.ec', 'role' => 'Estudiante', 'department' => '9.º EGB · Paralelo B', 'status' => 'Inactivo', 'last_seen' => 'Sin registro'],
                ['name' => 'Ana Lucía Pérez', 'email' => 'ana.perez@email.com', 'role' => 'Representante', 'department' => 'Representante de Juan C. Pérez', 'status' => 'Activo', 'last_seen' => '24/8/2026, 6:30:11 p. m.'],
                ['name' => 'Sofía Naranjo', 'email' => 'sofia.naranjo@email.com', 'role' => 'Representante', 'department' => 'Representante de María F. Ruiz', 'status' => 'Activo', 'last_seen' => 'Sin registro'],
            ],
            'courses' => [
                ['code' => 'MAT-8A', 'name' => 'Matemática', 'parallel' => 'A', 'students' => 28, 'average' => '8,6', 'room' => 'Aula 8A'],
                ['code' => 'LYL-8A', 'name' => 'Lengua y Literatura', 'parallel' => 'A', 'students' => 28, 'average' => '8,4', 'room' => 'Aula 8A'],
                ['code' => 'CCNN-8A', 'name' => 'Ciencias Naturales', 'parallel' => 'A', 'students' => 28, 'average' => '8,2', 'room' => 'Lab. Ciencias'],
            ],
            'virtualCourses' => [
                [
                    'slug' => 'matematica-octavo', 'code' => 'MAT-8A', 'name' => 'Matemática · 8.º EGB',
                    'teacher' => 'Lcdo. Roberto Sánchez', 'initials' => 'RS', 'progress' => 78, 'tone' => 'indigo', 'icon' => 'calculator', 'icon' => 'book-open', 'icon' => 'calculator',
                    'parallel' => 'A', 'students' => 28, 'pending' => 7, 'sections' => 6, 'activities' => 12,
                    'room' => 'Aula 8A', 'updated' => 'Hoy, 08:45', 'visible' => true,
                    'readiness' => 92, 'image' => 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=900&h=520&fit=crop',
                    'next' => 'Cuestionario: Números racionales', 'date' => '31 AGO',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Números enteros y racionales', 'meta' => 'Guía de aprendizaje · PDF', 'done' => true],
                        ['type' => 'file', 'title' => 'Razones, proporciones y porcentajes', 'meta' => 'Ejercicios aplicados · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'Geometría y medición en nuestro entorno', 'meta' => 'Video interactivo · 24 min', 'done' => true],
                        ['type' => 'task', 'title' => 'Proyecto: presupuesto familiar responsable', 'meta' => 'Entrega: 31 de agosto · 20:00', 'done' => false],
                    ],
                    'grades' => [['Evaluación diagnóstica', '9,0'], ['Taller de números racionales', '8,8'], ['Cuestionario unidad 1', '8,9']],
                ],
                [
                    'slug' => 'lengua-literatura-octavo', 'code' => 'LYL-8A', 'name' => 'Lengua y Literatura · 8.º EGB',
                    'teacher' => 'Lcda. Patricia Morales', 'initials' => 'PM', 'progress' => 62, 'tone' => 'violet', 'icon' => 'book-open',
                    'parallel' => 'A', 'students' => 28, 'pending' => 11, 'sections' => 5, 'activities' => 9,
                    'room' => 'Aula 8A', 'updated' => 'Ayer, 16:20', 'visible' => true,
                    'readiness' => 84, 'image' => 'https://images.unsplash.com/photo-1455885666463-5e7c6f3b71b9?w=900&h=520&fit=crop',
                    'next' => 'Reseña: Relato ecuatoriano', 'date' => '02 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Narraciones de tradición oral', 'meta' => 'Antología · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'El cuento latinoamericano', 'meta' => 'Video · 31 min', 'done' => true],
                        ['type' => 'file', 'title' => 'Comunicación oral y argumentación', 'meta' => 'Guía práctica · PDF', 'done' => false],
                        ['type' => 'task', 'title' => 'Taller de escritura: mi comunidad', 'meta' => 'Entrega: 2 de septiembre · 20:00', 'done' => false],
                    ],
                    'grades' => [['Comprensión lectora', '8,2'], ['Taller de escritura', '8,6'], ['Reseña literaria', '8,4']],
                ],
                [
                    'slug' => 'ciencias-naturales-octavo', 'code' => 'CCNN-8A', 'name' => 'Ciencias Naturales · 8.º EGB',
                    'teacher' => 'Lcda. Ana Gómez', 'initials' => 'AG', 'progress' => 86, 'tone' => 'green', 'icon' => 'flask-conical',
                    'parallel' => 'A', 'students' => 28, 'pending' => 4, 'sections' => 7, 'activities' => 14,
                    'room' => 'Lab. Ciencias', 'updated' => '25 ago, 11:10', 'visible' => true,
                    'readiness' => 76, 'image' => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=900&h=520&fit=crop',
                    'next' => 'Experimento: Fotosíntesis', 'date' => '04 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Ecosistemas y biodiversidad', 'meta' => 'Guía de campo · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'La célula y sus funciones', 'meta' => 'Video · 28 min', 'done' => true],
                        ['type' => 'file', 'title' => 'Nutrición, salud y bienestar', 'meta' => 'Laboratorio guiado · PDF', 'done' => true],
                        ['type' => 'task', 'title' => 'Práctica: observación de células vegetales', 'meta' => 'Entrega: 4 de septiembre · 18:00', 'done' => false],
                    ],
                    'grades' => [['Mapa de ecosistemas', '8,7'], ['Cuestionario 1', '9,1'], ['Informe de laboratorio', '8,6']],
                ],
                [
                    'slug' => 'estudios-sociales-octavo', 'code' => 'EESS-8A', 'name' => 'Estudios Sociales · 8.º EGB',
                    'teacher' => 'Lcdo. Fernando Ruiz', 'initials' => 'FR', 'progress' => 71, 'tone' => 'amber', 'icon' => 'globe',
                    'parallel' => 'A', 'students' => 28, 'pending' => 6, 'sections' => 6, 'activities' => 10,
                    'room' => 'Aula 8A', 'updated' => 'Hoy, 07:40', 'visible' => true,
                    'readiness' => 88, 'image' => 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=900&h=520&fit=crop',
                    'next' => 'Línea de tiempo: Ecuador republicano', 'date' => '05 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Identidad y diversidad cultural', 'meta' => 'Lectura guiada · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'Ecuador en el siglo XIX', 'meta' => 'Documental · 22 min', 'done' => true],
                        ['type' => 'file', 'title' => 'Ciudadanía, derechos y participación', 'meta' => 'Estudio de casos · PDF', 'done' => false],
                        ['type' => 'task', 'title' => 'Proyecto: memoria de mi comunidad', 'meta' => 'Entrega: 5 de septiembre · 18:00', 'done' => false],
                    ],
                    'grades' => [['Mapa político del Ecuador', '8,5'], ['Debate de ciudadanía', '8,9'], ['Línea de tiempo', '8,6']],
                ],
                [
                    'slug' => 'english-octavo', 'code' => 'ENG-8A', 'name' => 'English · 8.º EGB',
                    'teacher' => 'Miss Carolina Mendoza', 'initials' => 'CM', 'progress' => 69, 'tone' => 'rose', 'icon' => 'languages',
                    'parallel' => 'A', 'students' => 28, 'pending' => 8, 'sections' => 5, 'activities' => 11,
                    'room' => 'Aula de Idiomas', 'updated' => 'Ayer, 14:15', 'visible' => true,
                    'readiness' => 90, 'image' => 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=900&h=520&fit=crop',
                    'next' => 'Speaking task: My community', 'date' => '06 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Daily life and routines', 'meta' => 'Learning guide · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'Stories from Ecuador', 'meta' => 'Interactive video · 18 min', 'done' => true],
                        ['type' => 'file', 'title' => 'People, places and traditions', 'meta' => 'Vocabulary lab · PDF', 'done' => false],
                        ['type' => 'task', 'title' => 'Speaking project: my community', 'meta' => 'Due: September 6 · 18:00', 'done' => false],
                    ],
                    'grades' => [['Diagnostic quiz', '8,8'], ['Reading journal', '8,5'], ['Speaking task', '8,7']],
                ],
                [
                    'slug' => 'computacion-robotica-octavo', 'code' => 'COMP-8A', 'name' => 'Computación y Robótica · 8.º EGB',
                    'teacher' => 'Lcdo. Carlos Mendoza', 'initials' => 'CM', 'progress' => 83, 'tone' => 'cyan', 'icon' => 'monitor',
                    'parallel' => 'A', 'students' => 28, 'pending' => 5, 'sections' => 7, 'activities' => 13,
                    'room' => 'Sala de Computación', 'updated' => 'Hoy, 09:20', 'visible' => true,
                    'readiness' => 95, 'image' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=900&h=520&fit=crop',
                    'next' => 'Reto: secuencia para un robot', 'date' => '08 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Ciudadanía digital responsable', 'meta' => 'Guía práctica · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'Pensamiento computacional', 'meta' => 'Video interactivo · 26 min', 'done' => true],
                        ['type' => 'file', 'title' => 'Programación visual por bloques', 'meta' => 'Laboratorio guiado · PDF', 'done' => true],
                        ['type' => 'task', 'title' => 'Reto: secuencia para un robot', 'meta' => 'Entrega: 8 de septiembre · 17:00', 'done' => false],
                    ],
                    'grades' => [['Seguridad digital', '9,2'], ['Algoritmos cotidianos', '8,8'], ['Reto de robótica', '9,0']],
                ],
                [
                    'slug' => 'educacion-cultural-artistica-octavo', 'code' => 'ECA-8A', 'name' => 'Educación Cultural y Artística · 8.º EGB',
                    'teacher' => 'Lcda. Sofía Naranjo', 'initials' => 'SN', 'progress' => 58, 'tone' => 'pink', 'icon' => 'palette',
                    'parallel' => 'A', 'students' => 28, 'pending' => 9, 'sections' => 5, 'activities' => 8,
                    'room' => 'Taller de Arte', 'updated' => '26 ago, 12:10', 'visible' => true,
                    'readiness' => 81, 'image' => 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=900&h=520&fit=crop',
                    'next' => 'Galería: símbolos de Riobamba', 'date' => '09 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Lenguajes del arte', 'meta' => 'Cuaderno creativo · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'Patrimonio cultural de Riobamba', 'meta' => 'Recorrido visual · 19 min', 'done' => true],
                        ['type' => 'file', 'title' => 'Color, forma y composición', 'meta' => 'Taller visual · PDF', 'done' => false],
                        ['type' => 'task', 'title' => 'Galería: símbolos de Riobamba', 'meta' => 'Entrega: 9 de septiembre · 16:00', 'done' => false],
                    ],
                    'grades' => [['Bitácora visual', '8,6'], ['Composición artística', '9,0'], ['Galería escolar', '8,8']],
                ],
                [
                    'slug' => 'educacion-fisica-octavo', 'code' => 'EF-8A', 'name' => 'Educación Física · 8.º EGB',
                    'teacher' => 'Lcdo. Diego Vera', 'initials' => 'DV', 'progress' => 77, 'tone' => 'teal', 'icon' => 'volleyball',
                    'parallel' => 'A', 'students' => 28, 'pending' => 3, 'sections' => 6, 'activities' => 9,
                    'room' => 'Cancha cubierta', 'updated' => '25 ago, 10:30', 'visible' => true,
                    'readiness' => 87, 'image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=900&h=520&fit=crop',
                    'next' => 'Circuito de coordinación y equilibrio', 'date' => '10 SEP',
                    'modules' => [
                        ['type' => 'file', 'title' => 'Bienestar y condición física', 'meta' => 'Ficha de autocuidado · PDF', 'done' => true],
                        ['type' => 'video', 'title' => 'Coordinación y equilibrio', 'meta' => 'Demostración · 15 min', 'done' => true],
                        ['type' => 'file', 'title' => 'Juegos cooperativos y convivencia', 'meta' => 'Guía de práctica · PDF', 'done' => true],
                        ['type' => 'task', 'title' => 'Reto: circuito personal de movimiento', 'meta' => 'Entrega: 10 de septiembre · 15:00', 'done' => false],
                    ],
                    'grades' => [['Diagnóstico físico', '9,0'], ['Trabajo en equipo', '9,2'], ['Circuito de coordinación', '9,1']],
                ],
            ],
            'roster' => [
                ['name' => 'María Fernanda Ruiz', 'code' => '202145678', 'p1' => '8,7', 'p2' => '9,1', 'final' => '8,9', 'status' => 'Aprobado'],
                ['name' => 'Jorge Silva Andrade', 'code' => '202145702', 'p1' => '7,2', 'p2' => '6,8', 'final' => '7,0', 'status' => 'Aprobado'],
                ['name' => 'Juan Carlos Pérez', 'code' => '202145711', 'p1' => '8,2', 'p2' => '8,6', 'final' => '8,4', 'status' => 'Aprobado'],
                ['name' => 'Diana Carolina Vaca', 'code' => '202145733', 'p1' => '5,4', 'p2' => '6,1', 'final' => '5,8', 'status' => 'En riesgo'],
                ['name' => 'Luis Alberto Naranjo', 'code' => '202145750', 'p1' => '9,0', 'p2' => '9,4', 'final' => '9,2', 'status' => 'Aprobado'],
            ],
            'grades' => [
                ['subject' => 'Matemática', 'p1' => '8,7', 'p2' => '9,1', 'final' => '8,9', 'status' => 'Aprobado'],
                ['subject' => 'Lengua y Literatura', 'p1' => '8,2', 'p2' => '8,5', 'final' => '8,4', 'status' => 'Aprobado'],
                ['subject' => 'Ciencias Naturales', 'p1' => '9,0', 'p2' => '8,8', 'final' => '8,9', 'status' => 'Aprobado'],
                ['subject' => 'Estudios Sociales', 'p1' => '7,8', 'p2' => '8,1', 'final' => '8,0', 'status' => 'Aprobado'],
                ['subject' => 'English', 'p1' => '8,5', 'p2' => '9,0', 'final' => '8,8', 'status' => 'Aprobado'],
            ],
            'notices' => [
                ['type' => 'Académico', 'title' => 'Reunión de seguimiento del quimestre', 'text' => 'Miércoles 2 de septiembre, 16:00 · Salón de actos.', 'date' => 'Hoy'],
                ['type' => 'Docente', 'title' => 'Nuevo material en Ciencias Naturales', 'text' => 'Se publicó la guía de observación de ecosistemas.', 'date' => 'Ayer'],
                ['type' => 'Sistema', 'title' => 'Solicitud de equipo aprobada', 'text' => 'La solicitud SOL-2026-041 está lista para retiro.', 'date' => '25 ago'],
            ],
            'assignments' => [
                ['code' => 'EQ001', 'asset' => 'Multímetro Digital Fluke', 'holder' => 'Ing. Roberto Sánchez', 'place' => 'Lab. Circuitos', 'since' => '12 ago 2026', 'status' => 'Activa'],
                ['code' => 'EQ008', 'asset' => 'Kit educativo de robótica', 'holder' => 'Lcda. Patricia Morales', 'place' => 'Sala de Computación', 'since' => '18 ago 2026', 'status' => 'Activa'],
                ['code' => 'EQ007', 'asset' => 'Proyector Epson PowerLite', 'holder' => 'Secretaría General', 'place' => 'Auditorio', 'since' => '02 ago 2026', 'status' => 'Activa'],
                ['code' => 'EQ011', 'asset' => 'Protoboard 2390 puntos', 'holder' => 'Ing. Fernando Ruiz', 'place' => 'Lab. Electrónica', 'since' => '25 jul 2026', 'status' => 'Devuelta'],
            ],
            'maintenance' => [
                ['order' => 'OM-2026-014', 'asset' => 'Osciloscopio Tektronix', 'issue' => 'Canal 2 sin señal', 'priority' => 'Alta', 'opened' => '20 ago 2026', 'status' => 'Pendiente'],
                ['order' => 'OM-2026-012', 'asset' => 'Computadora Core i7', 'issue' => 'Fuente de poder dañada', 'priority' => 'Alta', 'opened' => '17 ago 2026', 'status' => 'En proceso'],
                ['order' => 'OM-2026-009', 'asset' => 'Proyector Epson PowerLite', 'issue' => 'Lámpara con bajo brillo', 'priority' => 'Media', 'opened' => '09 ago 2026', 'status' => 'En proceso'],
                ['order' => 'OM-2026-004', 'asset' => 'Motor Trifásico WEG', 'issue' => 'Mantenimiento preventivo', 'priority' => 'Baja', 'opened' => '28 jul 2026', 'status' => 'Cerrada'],
            ],
            'reports' => [
                ['code' => 'REP-2026-018', 'name' => 'Uso de recursos por mes', 'period' => 'Marzo - Agosto 2026', 'format' => 'PDF', 'author' => 'Dra. Andrea López', 'date' => '27 ago 2026', 'status' => 'Generado'],
                ['code' => 'REP-2026-017', 'name' => 'Solicitudes por estado', 'period' => 'Agosto 2026', 'format' => 'Excel', 'author' => 'Dra. Andrea López', 'date' => '25 ago 2026', 'status' => 'Generado'],
                ['code' => 'REP-2026-015', 'name' => 'Ocupación de aulas', 'period' => 'Año lectivo 2026-2027', 'format' => 'PDF', 'author' => 'Lcdo. Roberto Sánchez', 'date' => '18 ago 2026', 'status' => 'Generado'],
                ['code' => 'REP-2026-012', 'name' => 'Rendimiento académico por curso', 'period' => 'Parcial 1', 'format' => 'Excel', 'author' => 'Ing. Patricia Morales', 'date' => '09 ago 2026', 'status' => 'Generado'],
                ['code' => 'REP-2026-009', 'name' => 'Inventario de laboratorios', 'period' => 'Agosto 2026', 'format' => 'CSV', 'author' => 'Braulio Balseca', 'date' => '02 ago 2026', 'status' => 'Archivado'],
            ],
            'resources' => [
                ['title' => 'Guía de aprendizaje: Números racionales', 'subject' => 'Matemática', 'type' => 'PDF', 'size' => '2,4 MB'],
                ['title' => 'Antología de cuentos ecuatorianos', 'subject' => 'Lengua y Literatura', 'type' => 'PDF', 'size' => '3,1 MB'],
                ['title' => 'Ecosistemas del Ecuador', 'subject' => 'Ciencias Naturales', 'type' => 'VIDEO', 'size' => '18 min'],
                ['title' => 'Formato de proyecto interdisciplinario', 'subject' => 'General', 'type' => 'DOCX', 'size' => '680 KB'],
            ],
        ];
    }
}
